# Generated by Django 5.2.3 on 2025-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_conversation_options_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for the conversation', max_length=255, null=True),
        ),
    ]
